// Code generated by gen-version-data.go for go1.15 -- DO NOT EDIT.

package main

func init() {
	offsetsByVersion["go1.15"] = SymbolOffsetsForGo115
}

// SymbolOffsetsForGo115 includes the data on important symbols
// in the Go runtime for go1.15.
//
var SymbolOffsetsForGo115 = []SymbolOffset{
	{
		Symbol: "GO_STACK__SIZE",
		Offset: 16,
	},
	{
		Symbol: "GO_STACK_LO",
		Offset: 0,
	},
	{
		Symbol: "GO_STACK_HI",
		Offset: 8,
	},
	{
		Symbol: "GO_G__SIZE",
		Offset: 376,
	},
	{
		Symbol: "GO_G_STACK",
		Offset: 0,
	},
	{
		Symbol: "GO_G_STACKGUARD0",
		Offset: 16,
	},
	{
		Symbol: "GO_G_STACKGUARD1",
		Offset: 24,
	},
	{
		Symbol: "GO_G__PANIC",
		Offset: 32,
	},
	{
		Symbol: "GO_G__DEFER",
		Offset: 40,
	},
	{
		Symbol: "GO_G_M",
		Offset: 48,
	},
	{
		Symbol: "GO_G_SCHED",
		Offset: 56,
	},
	{
		Symbol: "GO_G_SYSCALLSP",
		Offset: 112,
	},
	{
		Symbol: "GO_G_SYSCALLPC",
		Offset: 120,
	},
	{
		Symbol: "GO_G_STKTOPSP",
		Offset: 128,
	},
	{
		Symbol: "GO_G_PARAM",
		Offset: 136,
	},
	{
		Symbol: "GO_G_ATOMICSTATUS",
		Offset: 144,
	},
	{
		Symbol: "GO_G_STACKLOCK",
		Offset: 148,
	},
	{
		Symbol: "GO_G_GOID",
		Offset: 152,
	},
	{
		Symbol: "GO_G_SCHEDLINK",
		Offset: 160,
	},
	{
		Symbol: "GO_G_WAITSINCE",
		Offset: 168,
	},
	{
		Symbol: "GO_G_WAITREASON",
		Offset: 176,
	},
	{
		Symbol: "GO_G_PREEMPT",
		Offset: 177,
	},
	{
		Symbol: "GO_G_PREEMPTSTOP",
		Offset: 178,
	},
	{
		Symbol: "GO_G_PREEMPTSHRINK",
		Offset: 179,
	},
	{
		Symbol: "GO_G_ASYNCSAFEPOINT",
		Offset: 180,
	},
	{
		Symbol: "GO_G_PANICONFAULT",
		Offset: 181,
	},
	{
		Symbol: "GO_G_GCSCANDONE",
		Offset: 182,
	},
	{
		Symbol: "GO_G_THROWSPLIT",
		Offset: 183,
	},
	{
		Symbol: "GO_G_ACTIVESTACKCHANS",
		Offset: 184,
	},
	{
		Symbol: "GO_G_PARKINGONCHAN",
		Offset: 185,
	},
	{
		Symbol: "GO_G_RACEIGNORE",
		Offset: 186,
	},
	{
		Symbol: "GO_G_SYSBLOCKTRACED",
		Offset: 187,
	},
	{
		Symbol: "GO_G_SYSEXITTICKS",
		Offset: 192,
	},
	{
		Symbol: "GO_G_TRACESEQ",
		Offset: 200,
	},
	{
		Symbol: "GO_G_TRACELASTP",
		Offset: 208,
	},
	{
		Symbol: "GO_G_LOCKEDM",
		Offset: 216,
	},
	{
		Symbol: "GO_G_SIG",
		Offset: 224,
	},
	{
		Symbol: "GO_G_WRITEBUF",
		Offset: 232,
	},
	{
		Symbol: "GO_G_SIGCODE0",
		Offset: 256,
	},
	{
		Symbol: "GO_G_SIGCODE1",
		Offset: 264,
	},
	{
		Symbol: "GO_G_SIGPC",
		Offset: 272,
	},
	{
		Symbol: "GO_G_GOPC",
		Offset: 280,
	},
	{
		Symbol: "GO_G_ANCESTORS",
		Offset: 288,
	},
	{
		Symbol: "GO_G_STARTPC",
		Offset: 296,
	},
	{
		Symbol: "GO_G_RACECTX",
		Offset: 304,
	},
	{
		Symbol: "GO_G_WAITING",
		Offset: 312,
	},
	{
		Symbol: "GO_G_CGOCTXT",
		Offset: 320,
	},
	{
		Symbol: "GO_G_LABELS",
		Offset: 344,
	},
	{
		Symbol: "GO_G_TIMER",
		Offset: 352,
	},
	{
		Symbol: "GO_G_SELECTDONE",
		Offset: 360,
	},
	{
		Symbol: "GO_G_GCASSISTBYTES",
		Offset: 368,
	},
	{
		Symbol: "GO_M__SIZE",
		Offset: 992,
	},
	{
		Symbol: "GO_M_G0",
		Offset: 0,
	},
	{
		Symbol: "GO_M_MOREBUF",
		Offset: 8,
	},
	{
		Symbol: "GO_M_DIVMOD",
		Offset: 64,
	},
	{
		Symbol: "GO_M_PROCID",
		Offset: 72,
	},
	{
		Symbol: "GO_M_GSIGNAL",
		Offset: 80,
	},
	{
		Symbol: "GO_M_GOSIGSTACK",
		Offset: 88,
	},
	{
		Symbol: "GO_M_SIGMASK",
		Offset: 128,
	},
	{
		Symbol: "GO_M_TLS",
		Offset: 136,
	},
	{
		Symbol: "GO_M_MSTARTFN",
		Offset: 184,
	},
	{
		Symbol: "GO_M_CURG",
		Offset: 192,
	},
	{
		Symbol: "GO_M_CAUGHTSIG",
		Offset: 200,
	},
	{
		Symbol: "GO_M_P",
		Offset: 208,
	},
	{
		Symbol: "GO_M_NEXTP",
		Offset: 216,
	},
	{
		Symbol: "GO_M_OLDP",
		Offset: 224,
	},
	{
		Symbol: "GO_M_ID",
		Offset: 232,
	},
	{
		Symbol: "GO_M_MALLOCING",
		Offset: 240,
	},
	{
		Symbol: "GO_M_THROWING",
		Offset: 244,
	},
	{
		Symbol: "GO_M_PREEMPTOFF",
		Offset: 248,
	},
	{
		Symbol: "GO_M_LOCKS",
		Offset: 264,
	},
	{
		Symbol: "GO_M_DYING",
		Offset: 268,
	},
	{
		Symbol: "GO_M_PROFILEHZ",
		Offset: 272,
	},
	{
		Symbol: "GO_M_SPINNING",
		Offset: 276,
	},
	{
		Symbol: "GO_M_BLOCKED",
		Offset: 277,
	},
	{
		Symbol: "GO_M_NEWSIGSTACK",
		Offset: 278,
	},
	{
		Symbol: "GO_M_PRINTLOCK",
		Offset: 279,
	},
	{
		Symbol: "GO_M_INCGO",
		Offset: 280,
	},
	{
		Symbol: "GO_M_FREEWAIT",
		Offset: 284,
	},
	{
		Symbol: "GO_M_FASTRAND",
		Offset: 288,
	},
	{
		Symbol: "GO_M_NEEDEXTRAM",
		Offset: 296,
	},
	{
		Symbol: "GO_M_TRACEBACK",
		Offset: 297,
	},
	{
		Symbol: "GO_M_NCGOCALL",
		Offset: 304,
	},
	{
		Symbol: "GO_M_NCGO",
		Offset: 312,
	},
	{
		Symbol: "GO_M_CGOCALLERSUSE",
		Offset: 316,
	},
	{
		Symbol: "GO_M_CGOCALLERS",
		Offset: 320,
	},
	{
		Symbol: "GO_M_PARK",
		Offset: 328,
	},
	{
		Symbol: "GO_M_ALLLINK",
		Offset: 336,
	},
	{
		Symbol: "GO_M_SCHEDLINK",
		Offset: 344,
	},
	{
		Symbol: "GO_M_LOCKEDG",
		Offset: 352,
	},
	{
		Symbol: "GO_M_CREATESTACK",
		Offset: 360,
	},
	{
		Symbol: "GO_M_LOCKEDEXT",
		Offset: 616,
	},
	{
		Symbol: "GO_M_LOCKEDINT",
		Offset: 620,
	},
	{
		Symbol: "GO_M_NEXTWAITM",
		Offset: 624,
	},
	{
		Symbol: "GO_M_WAITUNLOCKF",
		Offset: 632,
	},
	{
		Symbol: "GO_M_WAITLOCK",
		Offset: 640,
	},
	{
		Symbol: "GO_M_WAITTRACEEV",
		Offset: 648,
	},
	{
		Symbol: "GO_M_WAITTRACESKIP",
		Offset: 656,
	},
	{
		Symbol: "GO_M_STARTINGTRACE",
		Offset: 664,
	},
	{
		Symbol: "GO_M_SYSCALLTICK",
		Offset: 668,
	},
	{
		Symbol: "GO_M_FREELINK",
		Offset: 672,
	},
	{
		Symbol: "GO_M_LIBCALL",
		Offset: 680,
	},
	{
		Symbol: "GO_M_LIBCALLPC",
		Offset: 728,
	},
	{
		Symbol: "GO_M_LIBCALLSP",
		Offset: 736,
	},
	{
		Symbol: "GO_M_LIBCALLG",
		Offset: 744,
	},
	{
		Symbol: "GO_M_SYSCALL",
		Offset: 752,
	},
	{
		Symbol: "GO_M_VDSOSP",
		Offset: 800,
	},
	{
		Symbol: "GO_M_VDSOPC",
		Offset: 808,
	},
	{
		Symbol: "GO_M_PREEMPTGEN",
		Offset: 816,
	},
	{
		Symbol: "GO_M_SIGNALPENDING",
		Offset: 820,
	},
	{
		Symbol: "GO_M_DLOGPERM",
		Offset: 824,
	},
	{
		Symbol: "GO_M_MOS",
		Offset: 824,
	},
	{
		Symbol: "GO_M_LOCKSHELDLEN",
		Offset: 824,
	},
	{
		Symbol: "GO_M_LOCKSHELD",
		Offset: 832,
	},
}
