// Code generated by gen-version-data.go for go1.8 -- DO NOT EDIT.

package main

func init() {
	offsetsByVersion["go1.8"] = SymbolOffsetsForGo18
}

// SymbolOffsetsForGo18 includes the data on important symbols
// in the Go runtime for go1.8.
//
var SymbolOffsetsForGo18 = []SymbolOffset{
	{
		Symbol: "GO_STACK__SIZE",
		Offset: 16,
	},
	{
		Symbol: "GO_STACK_LO",
		Offset: 0,
	},
	{
		Symbol: "GO_STACK_HI",
		Offset: 8,
	},
	{
		Symbol: "GO_G__SIZE",
		Offset: 400,
	},
	{
		Symbol: "GO_G_STACK",
		Offset: 0,
	},
	{
		Symbol: "GO_G_STACKGUARD0",
		Offset: 16,
	},
	{
		Symbol: "GO_G_STACKGUARD1",
		Offset: 24,
	},
	{
		Symbol: "GO_G__PANIC",
		Offset: 32,
	},
	{
		Symbol: "GO_G__DEFER",
		Offset: 40,
	},
	{
		Symbol: "GO_G_M",
		Offset: 48,
	},
	{
		Symbol: "GO_G_STACKALLOC",
		Offset: 56,
	},
	{
		Symbol: "GO_G_SCHED",
		Offset: 64,
	},
	{
		Symbol: "GO_G_SYSCALLSP",
		Offset: 120,
	},
	{
		Symbol: "GO_G_SYSCALLPC",
		Offset: 128,
	},
	{
		Symbol: "GO_G_STKBAR",
		Offset: 136,
	},
	{
		Symbol: "GO_G_STKBARPOS",
		Offset: 160,
	},
	{
		Symbol: "GO_G_STKTOPSP",
		Offset: 168,
	},
	{
		Symbol: "GO_G_PARAM",
		Offset: 176,
	},
	{
		Symbol: "GO_G_ATOMICSTATUS",
		Offset: 184,
	},
	{
		Symbol: "GO_G_STACKLOCK",
		Offset: 188,
	},
	{
		Symbol: "GO_G_GOID",
		Offset: 192,
	},
	{
		Symbol: "GO_G_WAITSINCE",
		Offset: 200,
	},
	{
		Symbol: "GO_G_WAITREASON",
		Offset: 208,
	},
	{
		Symbol: "GO_G_SCHEDLINK",
		Offset: 224,
	},
	{
		Symbol: "GO_G_PREEMPT",
		Offset: 232,
	},
	{
		Symbol: "GO_G_PANICONFAULT",
		Offset: 233,
	},
	{
		Symbol: "GO_G_PREEMPTSCAN",
		Offset: 234,
	},
	{
		Symbol: "GO_G_GCSCANDONE",
		Offset: 235,
	},
	{
		Symbol: "GO_G_GCSCANVALID",
		Offset: 236,
	},
	{
		Symbol: "GO_G_THROWSPLIT",
		Offset: 237,
	},
	{
		Symbol: "GO_G_RACEIGNORE",
		Offset: 238,
	},
	{
		Symbol: "GO_G_SYSBLOCKTRACED",
		Offset: 239,
	},
	{
		Symbol: "GO_G_SYSEXITTICKS",
		Offset: 240,
	},
	{
		Symbol: "GO_G_TRACESEQ",
		Offset: 248,
	},
	{
		Symbol: "GO_G_TRACELASTP",
		Offset: 256,
	},
	{
		Symbol: "GO_G_LOCKEDM",
		Offset: 264,
	},
	{
		Symbol: "GO_G_SIG",
		Offset: 272,
	},
	{
		Symbol: "GO_G_WRITEBUF",
		Offset: 280,
	},
	{
		Symbol: "GO_G_SIGCODE0",
		Offset: 304,
	},
	{
		Symbol: "GO_G_SIGCODE1",
		Offset: 312,
	},
	{
		Symbol: "GO_G_SIGPC",
		Offset: 320,
	},
	{
		Symbol: "GO_G_GOPC",
		Offset: 328,
	},
	{
		Symbol: "GO_G_STARTPC",
		Offset: 336,
	},
	{
		Symbol: "GO_G_RACECTX",
		Offset: 344,
	},
	{
		Symbol: "GO_G_WAITING",
		Offset: 352,
	},
	{
		Symbol: "GO_G_CGOCTXT",
		Offset: 360,
	},
	{
		Symbol: "GO_G_GCRESCAN",
		Offset: 384,
	},
	{
		Symbol: "GO_G_GCASSISTBYTES",
		Offset: 392,
	},
	{
		Symbol: "GO_M__SIZE",
		Offset: 936,
	},
	{
		Symbol: "GO_M_G0",
		Offset: 0,
	},
	{
		Symbol: "GO_M_MOREBUF",
		Offset: 8,
	},
	{
		Symbol: "GO_M_DIVMOD",
		Offset: 64,
	},
	{
		Symbol: "GO_M_PROCID",
		Offset: 72,
	},
	{
		Symbol: "GO_M_GSIGNAL",
		Offset: 80,
	},
	{
		Symbol: "GO_M_SIGMASK",
		Offset: 88,
	},
	{
		Symbol: "GO_M_TLS",
		Offset: 96,
	},
	{
		Symbol: "GO_M_MSTARTFN",
		Offset: 144,
	},
	{
		Symbol: "GO_M_CURG",
		Offset: 152,
	},
	{
		Symbol: "GO_M_CAUGHTSIG",
		Offset: 160,
	},
	{
		Symbol: "GO_M_P",
		Offset: 168,
	},
	{
		Symbol: "GO_M_NEXTP",
		Offset: 176,
	},
	{
		Symbol: "GO_M_ID",
		Offset: 184,
	},
	{
		Symbol: "GO_M_MALLOCING",
		Offset: 188,
	},
	{
		Symbol: "GO_M_THROWING",
		Offset: 192,
	},
	{
		Symbol: "GO_M_PREEMPTOFF",
		Offset: 200,
	},
	{
		Symbol: "GO_M_LOCKS",
		Offset: 216,
	},
	{
		Symbol: "GO_M_SOFTFLOAT",
		Offset: 220,
	},
	{
		Symbol: "GO_M_DYING",
		Offset: 224,
	},
	{
		Symbol: "GO_M_PROFILEHZ",
		Offset: 228,
	},
	{
		Symbol: "GO_M_HELPGC",
		Offset: 232,
	},
	{
		Symbol: "GO_M_SPINNING",
		Offset: 236,
	},
	{
		Symbol: "GO_M_BLOCKED",
		Offset: 237,
	},
	{
		Symbol: "GO_M_INWB",
		Offset: 238,
	},
	{
		Symbol: "GO_M_NEWSIGSTACK",
		Offset: 239,
	},
	{
		Symbol: "GO_M_PRINTLOCK",
		Offset: 240,
	},
	{
		Symbol: "GO_M_FASTRAND",
		Offset: 244,
	},
	{
		Symbol: "GO_M_NCGOCALL",
		Offset: 248,
	},
	{
		Symbol: "GO_M_NCGO",
		Offset: 256,
	},
	{
		Symbol: "GO_M_CGOCALLERSUSE",
		Offset: 260,
	},
	{
		Symbol: "GO_M_CGOCALLERS",
		Offset: 264,
	},
	{
		Symbol: "GO_M_PARK",
		Offset: 272,
	},
	{
		Symbol: "GO_M_ALLLINK",
		Offset: 280,
	},
	{
		Symbol: "GO_M_SCHEDLINK",
		Offset: 288,
	},
	{
		Symbol: "GO_M_MCACHE",
		Offset: 296,
	},
	{
		Symbol: "GO_M_LOCKEDG",
		Offset: 304,
	},
	{
		Symbol: "GO_M_CREATESTACK",
		Offset: 312,
	},
	{
		Symbol: "GO_M_FREGLO",
		Offset: 568,
	},
	{
		Symbol: "GO_M_FREGHI",
		Offset: 632,
	},
	{
		Symbol: "GO_M_FFLAG",
		Offset: 696,
	},
	{
		Symbol: "GO_M_LOCKED",
		Offset: 700,
	},
	{
		Symbol: "GO_M_NEXTWAITM",
		Offset: 704,
	},
	{
		Symbol: "GO_M_GCSTATS",
		Offset: 712,
	},
	{
		Symbol: "GO_M_NEEDEXTRAM",
		Offset: 752,
	},
	{
		Symbol: "GO_M_TRACEBACK",
		Offset: 753,
	},
	{
		Symbol: "GO_M_WAITUNLOCKF",
		Offset: 760,
	},
	{
		Symbol: "GO_M_WAITLOCK",
		Offset: 768,
	},
	{
		Symbol: "GO_M_WAITTRACEEV",
		Offset: 776,
	},
	{
		Symbol: "GO_M_WAITTRACESKIP",
		Offset: 784,
	},
	{
		Symbol: "GO_M_STARTINGTRACE",
		Offset: 792,
	},
	{
		Symbol: "GO_M_SYSCALLTICK",
		Offset: 796,
	},
	{
		Symbol: "GO_M_THREAD",
		Offset: 800,
	},
	{
		Symbol: "GO_M_LIBCALL",
		Offset: 808,
	},
	{
		Symbol: "GO_M_LIBCALLPC",
		Offset: 856,
	},
	{
		Symbol: "GO_M_LIBCALLSP",
		Offset: 864,
	},
	{
		Symbol: "GO_M_LIBCALLG",
		Offset: 872,
	},
	{
		Symbol: "GO_M_SYSCALL",
		Offset: 880,
	},
	{
		Symbol: "GO_M_MOS",
		Offset: 928,
	},
}
