// Process the Go symbol offsets.

package main

import (
	"bytes"
	"fmt"
	"io/ioutil"
	"path/filepath"
)

// SymbolOffset represents the offset in memory where
// a symbol resides.
//
type SymbolOffset struct {
	Symbol string
	Offset uintptr
}

var offsetsByVersion = make(map[string][]SymbolOffset)

// GetOffsets determines the offset data for the current
// Go version, storing the results in ctx.Offsets.
//
func (ctx *Context) GetOffsets() {
	ctx.Offsets = offsetsByVersion[ctx.GoVersion]
	if ctx.Offsets == nil {
		ctx.Fatalf("no offsets data available for %s", ctx.GoVersion)
	}
}

// WriteOffsets writes the data in ctx.Offsets to
// ctx.WorkDir/go_asm_offsets.inc.
//
func (ctx *Context) WriteOffsets() {
	var buf bytes.Buffer

	// This file shouldn't be long-lived, but
	// we might as well write the warning just
	// in case.
	buf.WriteString(";; Code generated by WriteOffsets for ")
	buf.WriteString(ctx.GoVersion)
	buf.WriteString(" -- DO NOT EDIT.\n\n")

	for _, sym := range ctx.Offsets {
		fmt.Fprintf(&buf, "%s equ %#x ; %d\n", sym.Symbol, sym.Offset, sym.Offset)
	}

	name := "go_asm_offsets.inc"
	full := filepath.Join(ctx.WorkDir, name)
	err := ioutil.WriteFile(full, buf.Bytes(), 0644)
	if err != nil {
		ctx.Fatalf("failed to write symbol data to %s: %v", name, err)
	}
}
