# Copyright 2022 The Firefly Authors.
#
# Use of this source code is governed by a BSD 3-clause
# license that can be found in the LICENSE file.

[package]
name = "tar"
version = "0.1.0"
authors = ["Jamie Hall <the.sly.marbo@googlemail.com>"]
edition = "2018"

[lib]
name = "tar"
path = "lib.rs"

[dependencies]
align = {path = "../align"}
filesystem = {path = "../../filesystem"}
hex-literal = "=0.3.4"
serial = {path = "../../drivers/serial"}
sha2 = {version = "=0.10.1", default-features = false, features = ["force-soft"]}
storage = {path = "../../storage"}
