# Copyright 2022 The Firefly Authors.
#
# Use of this source code is governed by a BSD 3-clause
# license that can be found in the LICENSE file.

load("//bazel:qemu.bzl", "qemu")
load("//tools/bootimage:defs.bzl", "disk_image")

# Expose the license to the rest of the workspace.
exports_files(
    ["LICENSE"],
    visibility = ["//visibility:public"],
)

disk_image(
    name = "image",
    out = "image.bin",
    bootloader = "//bootloader",
    kernel = "//kernel",
    visibility = ["//visibility:public"],
)

qemu(
    name = "qemu",
    image = ":image",
    options = [
        "-serial",
        "stdio",
        "-display",
        "none",
        "-no-reboot",
        "-cpu",
        "Skylake-Server",
    ],
    qemu = "qemu-system-x86_64",
)

qemu(
    name = "qemu-gdb",
    image = ":image",
    options = [
        "-serial",
        "stdio",
        "-display",
        "none",
        "-no-reboot",
        "-cpu",
        "Skylake-Server",
        "-s",
        "-S",
    ],
    qemu = "qemu-system-x86_64",
)

qemu(
    name = "qemu-display",
    image = ":image",
    options = [
        "-serial",
        "stdio",
        "-no-reboot",
        "-cpu",
        "Skylake-Server",
    ],
    qemu = "qemu-system-x86_64",
)
