# Copyright 2022 The Firefly Authors.
#
# Use of this source code is governed by a BSD 3-clause
# license that can be found in the LICENSE file.

[package]
name = "virtio"
version = "0.1.0"
authors = ["Jamie Hall <the.sly.marbo@googlemail.com>"]
edition = "2018"

[lib]
name = "virtio"
path = "lib.rs"

[dependencies]
align = {path = "../../utils/align"}
bitflags = "=1.3.2"
bitmap_index = {path = "../../utils/bitmap_index"}
interrupts = {path = "../../interrupts"}
memlayout = {path = "../../memory/memlayout"}
mmio = {path = "../../memory/mmio"}
network = {path = "../../network"}
pci = {path = "../pci"}
physmem = {path = "../../memory/physmem"}
random = {path = "../../random"}
serial = {path = "../serial"}
smoltcp = {version = "=0.8.0", default-features = false, features = ["alloc", "async", "medium-ethernet", "proto-dhcpv4", "proto-ipv4", "socket", "socket-dhcpv4", "socket-raw", "socket-udp", "socket-tcp"]}
spin = "=0.9.2"
storage = {path = "../../storage"}
thread = {path = "../../multitasking/thread"}
virtmem = {path = "../../memory/virtmem"}
x86_64 = "=0.14.7"
