# Copyright 2022 The Firefly Authors.
#
# Use of this source code is governed by a BSD 3-clause
# license that can be found in the LICENSE file.

[package]
name = "serial"
version = "0.1.0"
authors = ["Jamie Hall <the.sly.marbo@googlemail.com>"]
edition = "2018"

[lib]
name = "serial"
path = "lib.rs"

[dependencies]
spin = "=0.9.2"
uart_16550 = "=0.2.15"
x86_64 = "=0.14.7"
