# Copyright 2022 The Firefly Authors.
#
# Use of this source code is governed by a BSD 3-clause
# license that can be found in the LICENSE file.

[package]
name = "mmio"
version = "0.1.0"
authors = ["Jamie Hall <the.sly.marbo@googlemail.com>"]
edition = "2018"

[lib]
name = "mmio"
path = "lib.rs"

[dependencies]
memlayout = {path = "../memlayout"}
physmem = {path = "../physmem"}
spin = "=0.9.2"
virtmem = {path = "../virtmem"}
x86_64 = "=0.14.7"
