// Copyright 2023 The Firefly Authors.
//
// Use of this source code is governed by a BSD 3-clause
// license that can be found in the LICENSE file.

// Abstract instructions emitted by the compiler.
// These are then transformed into concrete
// instructions specific to the target architecture,
// which is described as 'lowering'.

package main

var AbstractOps = []OpInfo{
	// Arithmetic ops.
	// Unary arithmetic.
	{Name: "Negate", Operands: 1},
	{Group: "Negate", Name: "NegateInt8", Operands: 1, Size: 8},
	{Group: "Negate", Name: "NegateInt16", Operands: 1, Size: 16},
	{Group: "Negate", Name: "NegateInt32", Operands: 1, Size: 32},
	{Group: "Negate", Name: "NegateInt64", Operands: 1, Size: 64},
	// Binary arithmetic.
	{Name: "AddString", Operands: 2},
	{Name: "Add", Operands: 2},
	{Group: "Add", Name: "AddInt8", Operands: 2, Size: 8, Commutative: true},
	{Group: "Add", Name: "AddInt16", Operands: 2, Size: 16, Commutative: true},
	{Group: "Add", Name: "AddInt32", Operands: 2, Size: 32, Commutative: true},
	{Group: "Add", Name: "AddInt64", Operands: 2, Size: 64, Commutative: true},
	{Group: "Add", Name: "AddUint8", Operands: 2, Size: 8, Commutative: true},
	{Group: "Add", Name: "AddUint16", Operands: 2, Size: 16, Commutative: true},
	{Group: "Add", Name: "AddUint32", Operands: 2, Size: 32, Commutative: true},
	{Group: "Add", Name: "AddUint64", Operands: 2, Size: 64, Commutative: true},
	{Name: "Subtract", Operands: 2, Commutative: true},
	{Group: "Subtract", Name: "SubtractInt8", Operands: 2, Size: 8, Commutative: true},
	{Group: "Subtract", Name: "SubtractInt16", Operands: 2, Size: 16, Commutative: true},
	{Group: "Subtract", Name: "SubtractInt32", Operands: 2, Size: 32, Commutative: true},
	{Group: "Subtract", Name: "SubtractInt64", Operands: 2, Size: 64, Commutative: true},
	{Group: "Subtract", Name: "SubtractUint8", Operands: 2, Size: 8, Commutative: true},
	{Group: "Subtract", Name: "SubtractUint16", Operands: 2, Size: 16, Commutative: true},
	{Group: "Subtract", Name: "SubtractUint32", Operands: 2, Size: 32, Commutative: true},
	{Group: "Subtract", Name: "SubtractUint64", Operands: 2, Size: 64, Commutative: true},
	{Name: "Multiply", Operands: 2, Commutative: true},
	{Group: "Multiply", Name: "MultiplyInt8", Operands: 2, Size: 8, Commutative: true},
	{Group: "Multiply", Name: "MultiplyInt16", Operands: 2, Size: 16, Commutative: true},
	{Group: "Multiply", Name: "MultiplyInt32", Operands: 2, Size: 32, Commutative: true},
	{Group: "Multiply", Name: "MultiplyInt64", Operands: 2, Size: 64, Commutative: true},
	{Group: "Multiply", Name: "MultiplyUint8", Operands: 2, Size: 8, Commutative: true},
	{Group: "Multiply", Name: "MultiplyUint16", Operands: 2, Size: 16, Commutative: true},
	{Group: "Multiply", Name: "MultiplyUint32", Operands: 2, Size: 32, Commutative: true},
	{Group: "Multiply", Name: "MultiplyUint64", Operands: 2, Size: 64, Commutative: true},
	{Name: "Divide", Operands: 2, Commutative: true},
	{Group: "Divide", Name: "DivideInt8", Operands: 2, Size: 8, Commutative: true},
	{Group: "Divide", Name: "DivideInt16", Operands: 2, Size: 16, Commutative: true},
	{Group: "Divide", Name: "DivideInt32", Operands: 2, Size: 32, Commutative: true},
	{Group: "Divide", Name: "DivideInt64", Operands: 2, Size: 64, Commutative: true},
	{Group: "Divide", Name: "DivideUint8", Operands: 2, Size: 8, Commutative: true},
	{Group: "Divide", Name: "DivideUint16", Operands: 2, Size: 16, Commutative: true},
	{Group: "Divide", Name: "DivideUint32", Operands: 2, Size: 32, Commutative: true},
	{Group: "Divide", Name: "DivideUint64", Operands: 2, Size: 64, Commutative: true},
	{Name: "BitwiseOr", Operands: 2, Commutative: true},
	{Group: "BitwiseOr", Name: "BitwiseOrInt8", Operands: 2, Size: 8, Commutative: true},
	{Group: "BitwiseOr", Name: "BitwiseOrInt16", Operands: 2, Size: 16, Commutative: true},
	{Group: "BitwiseOr", Name: "BitwiseOrInt32", Operands: 2, Size: 32, Commutative: true},
	{Group: "BitwiseOr", Name: "BitwiseOrInt64", Operands: 2, Size: 64, Commutative: true},
	{Group: "BitwiseOr", Name: "BitwiseOrUint8", Operands: 2, Size: 8, Commutative: true},
	{Group: "BitwiseOr", Name: "BitwiseOrUint16", Operands: 2, Size: 16, Commutative: true},
	{Group: "BitwiseOr", Name: "BitwiseOrUint32", Operands: 2, Size: 32, Commutative: true},
	{Group: "BitwiseOr", Name: "BitwiseOrUint64", Operands: 2, Size: 64, Commutative: true},
	{Name: "BitwiseAnd", Operands: 2, Commutative: true},
	{Group: "BitwiseAnd", Name: "BitwiseAndInt8", Operands: 2, Size: 8, Commutative: true},
	{Group: "BitwiseAnd", Name: "BitwiseAndInt16", Operands: 2, Size: 16, Commutative: true},
	{Group: "BitwiseAnd", Name: "BitwiseAndInt32", Operands: 2, Size: 32, Commutative: true},
	{Group: "BitwiseAnd", Name: "BitwiseAndInt64", Operands: 2, Size: 64, Commutative: true},
	{Group: "BitwiseAnd", Name: "BitwiseAndUint8", Operands: 2, Size: 8, Commutative: true},
	{Group: "BitwiseAnd", Name: "BitwiseAndUint16", Operands: 2, Size: 16, Commutative: true},
	{Group: "BitwiseAnd", Name: "BitwiseAndUint32", Operands: 2, Size: 32, Commutative: true},
	{Group: "BitwiseAnd", Name: "BitwiseAndUint64", Operands: 2, Size: 64, Commutative: true},
	{Name: "BitwiseXor", Operands: 2, Commutative: true},
	{Group: "BitwiseXor", Name: "BitwiseXorInt8", Operands: 2, Size: 8, Commutative: true},
	{Group: "BitwiseXor", Name: "BitwiseXorInt16", Operands: 2, Size: 16, Commutative: true},
	{Group: "BitwiseXor", Name: "BitwiseXorInt32", Operands: 2, Size: 32, Commutative: true},
	{Group: "BitwiseXor", Name: "BitwiseXorInt64", Operands: 2, Size: 64, Commutative: true},
	{Group: "BitwiseXor", Name: "BitwiseXorUint8", Operands: 2, Size: 8, Commutative: true},
	{Group: "BitwiseXor", Name: "BitwiseXorUint16", Operands: 2, Size: 16, Commutative: true},
	{Group: "BitwiseXor", Name: "BitwiseXorUint32", Operands: 2, Size: 32, Commutative: true},
	{Group: "BitwiseXor", Name: "BitwiseXorUint64", Operands: 2, Size: 64, Commutative: true},
	{Group: "LogicalOr", Name: "LogicalOr", Operands: 2, Commutative: true},
	{Group: "LogicalAnd", Name: "LogicalAnd", Operands: 2, Commutative: true},
	{Name: "ShiftLeft", Operands: 2, Commutative: true},
	{Group: "ShiftLeft", Name: "ShiftLeftInt8", Operands: 2, Size: 8, Commutative: true},
	{Group: "ShiftLeft", Name: "ShiftLeftInt16", Operands: 2, Size: 16, Commutative: true},
	{Group: "ShiftLeft", Name: "ShiftLeftInt32", Operands: 2, Size: 32, Commutative: true},
	{Group: "ShiftLeft", Name: "ShiftLeftInt64", Operands: 2, Size: 64, Commutative: true},
	{Group: "ShiftLeft", Name: "ShiftLeftUint8", Operands: 2, Size: 8, Commutative: true},
	{Group: "ShiftLeft", Name: "ShiftLeftUint16", Operands: 2, Size: 16, Commutative: true},
	{Group: "ShiftLeft", Name: "ShiftLeftUint32", Operands: 2, Size: 32, Commutative: true},
	{Group: "ShiftLeft", Name: "ShiftLeftUint64", Operands: 2, Size: 64, Commutative: true},
	{Name: "ShiftRight", Operands: 2, Commutative: true},
	{Group: "ShiftRight", Name: "ShiftRightInt8", Operands: 2, Size: 8, Commutative: true},
	{Group: "ShiftRight", Name: "ShiftRightInt16", Operands: 2, Size: 16, Commutative: true},
	{Group: "ShiftRight", Name: "ShiftRightInt32", Operands: 2, Size: 32, Commutative: true},
	{Group: "ShiftRight", Name: "ShiftRightInt64", Operands: 2, Size: 64, Commutative: true},
	{Group: "ShiftRight", Name: "ShiftRightUint8", Operands: 2, Size: 8, Commutative: true},
	{Group: "ShiftRight", Name: "ShiftRightUint16", Operands: 2, Size: 16, Commutative: true},
	{Group: "ShiftRight", Name: "ShiftRightUint32", Operands: 2, Size: 32, Commutative: true},
	{Group: "ShiftRight", Name: "ShiftRightUint64", Operands: 2, Size: 64, Commutative: true},
	{Name: "Equal", Operands: 2},
	{Group: "Equal", Name: "EqualInt8", Operands: 2, Size: 8},
	{Group: "Equal", Name: "EqualInt16", Operands: 2, Size: 16},
	{Group: "Equal", Name: "EqualInt32", Operands: 2, Size: 32},
	{Group: "Equal", Name: "EqualInt64", Operands: 2, Size: 64},
	{Group: "Equal", Name: "EqualUint8", Operands: 2, Size: 8},
	{Group: "Equal", Name: "EqualUint16", Operands: 2, Size: 16},
	{Group: "Equal", Name: "EqualUint32", Operands: 2, Size: 32},
	{Group: "Equal", Name: "EqualUint64", Operands: 2, Size: 64},
	{Name: "NotEqual", Operands: 2},
	{Group: "NotEqual", Name: "NotEqualInt8", Operands: 2, Size: 8},
	{Group: "NotEqual", Name: "NotEqualInt16", Operands: 2, Size: 16},
	{Group: "NotEqual", Name: "NotEqualInt32", Operands: 2, Size: 32},
	{Group: "NotEqual", Name: "NotEqualInt64", Operands: 2, Size: 64},
	{Group: "NotEqual", Name: "NotEqualUint8", Operands: 2, Size: 8},
	{Group: "NotEqual", Name: "NotEqualUint16", Operands: 2, Size: 16},
	{Group: "NotEqual", Name: "NotEqualUint32", Operands: 2, Size: 32},
	{Group: "NotEqual", Name: "NotEqualUint64", Operands: 2, Size: 64},
	{Name: "LessThan", Operands: 2},
	{Group: "LessThan", Name: "LessThanInt8", Operands: 2, Size: 8},
	{Group: "LessThan", Name: "LessThanInt16", Operands: 2, Size: 16},
	{Group: "LessThan", Name: "LessThanInt32", Operands: 2, Size: 32},
	{Group: "LessThan", Name: "LessThanInt64", Operands: 2, Size: 64},
	{Group: "LessThan", Name: "LessThanUint8", Operands: 2, Size: 8},
	{Group: "LessThan", Name: "LessThanUint16", Operands: 2, Size: 16},
	{Group: "LessThan", Name: "LessThanUint32", Operands: 2, Size: 32},
	{Group: "LessThan", Name: "LessThanUint64", Operands: 2, Size: 64},
	{Name: "LessThanOrEqual", Operands: 2},
	{Group: "LessThanOrEqual", Name: "LessThanOrEqualInt8", Operands: 2, Size: 8},
	{Group: "LessThanOrEqual", Name: "LessThanOrEqualInt16", Operands: 2, Size: 16},
	{Group: "LessThanOrEqual", Name: "LessThanOrEqualInt32", Operands: 2, Size: 32},
	{Group: "LessThanOrEqual", Name: "LessThanOrEqualInt64", Operands: 2, Size: 64},
	{Group: "LessThanOrEqual", Name: "LessThanOrEqualUint8", Operands: 2, Size: 8},
	{Group: "LessThanOrEqual", Name: "LessThanOrEqualUint16", Operands: 2, Size: 16},
	{Group: "LessThanOrEqual", Name: "LessThanOrEqualUint32", Operands: 2, Size: 32},
	{Group: "LessThanOrEqual", Name: "LessThanOrEqualUint64", Operands: 2, Size: 64},
	{Name: "GreaterThan", Operands: 2},
	{Group: "GreaterThan", Name: "GreaterThanInt8", Operands: 2, Size: 8},
	{Group: "GreaterThan", Name: "GreaterThanInt16", Operands: 2, Size: 16},
	{Group: "GreaterThan", Name: "GreaterThanInt32", Operands: 2, Size: 32},
	{Group: "GreaterThan", Name: "GreaterThanInt64", Operands: 2, Size: 64},
	{Group: "GreaterThan", Name: "GreaterThanUint8", Operands: 2, Size: 8},
	{Group: "GreaterThan", Name: "GreaterThanUint16", Operands: 2, Size: 16},
	{Group: "GreaterThan", Name: "GreaterThanUint32", Operands: 2, Size: 32},
	{Group: "GreaterThan", Name: "GreaterThanUint64", Operands: 2, Size: 64},
	{Name: "GreaterThanOrEqual", Operands: 2},
	{Group: "GreaterThanOrEqual", Name: "GreaterThanOrEqualInt8", Operands: 2, Size: 8},
	{Group: "GreaterThanOrEqual", Name: "GreaterThanOrEqualInt16", Operands: 2, Size: 16},
	{Group: "GreaterThanOrEqual", Name: "GreaterThanOrEqualInt32", Operands: 2, Size: 32},
	{Group: "GreaterThanOrEqual", Name: "GreaterThanOrEqualInt64", Operands: 2, Size: 64},
	{Group: "GreaterThanOrEqual", Name: "GreaterThanOrEqualUint8", Operands: 2, Size: 8},
	{Group: "GreaterThanOrEqual", Name: "GreaterThanOrEqualUint16", Operands: 2, Size: 16},
	{Group: "GreaterThanOrEqual", Name: "GreaterThanOrEqualUint32", Operands: 2, Size: 32},
	{Group: "GreaterThanOrEqual", Name: "GreaterThanOrEqualUint64", Operands: 2, Size: 64},
	// Constant values.
	{Name: "Constant"},
	{Group: "Constant", Name: "ConstantBool"},   // ExtraInt is 0 for false and 1 for true.
	{Group: "Constant", Name: "ConstantString"}, // Extra is the string value.
	{Group: "Constant", Name: "ConstantInt8", Size: 8},
	{Group: "Constant", Name: "ConstantInt16", Size: 16},
	{Group: "Constant", Name: "ConstantInt32", Size: 32},
	{Group: "Constant", Name: "ConstantInt64", Size: 64},
	{Group: "Constant", Name: "ConstantUint8", Size: 8},
	{Group: "Constant", Name: "ConstantUint16", Size: 16},
	{Group: "Constant", Name: "ConstantUint32", Size: 32},
	{Group: "Constant", Name: "ConstantUint64", Size: 64},
	{Group: "Constant", Name: "ConstantUntypedInt"}, // Extra is the constant.Value.
	// Memory operations.
	{Name: "Drop", Operands: 1}, // Used for debugging only.
	{Name: "Copy", Operands: 1}, // Output = operand 0.
	{Name: "MakeMemoryState", Virtual: true},
	{Name: "Parameter", Virtual: true}, // ExtraInt is the parameter index into Function.Type.Params.
	{Name: "MakeResult", Operands: -1},
	{Name: "FunctionCall", Operands: -1},
	{Name: "SaveRegister", Operands: 1},    // Extra is a register to save.
	{Name: "RestoreRegister", Operands: 1}, // Extra is a register to restore.
	// Strings.
	{Name: "StringPtr", Operands: 1},
	{Name: "StringLen", Operands: 1},
	// Numerical casts.
	{Name: "Cast", Operands: 1},
	{Group: "Cast", Name: "CastInt8ToInt16", Operands: 1, Size: 16},
	{Group: "Cast", Name: "CastInt8ToInt32", Operands: 1, Size: 32},
	{Group: "Cast", Name: "CastInt8ToInt64", Operands: 1, Size: 64},
	{Group: "Cast", Name: "CastInt8ToUint8", Operands: 1, Size: 8},
	{Group: "Cast", Name: "CastInt8ToUint16", Operands: 1, Size: 16},
	{Group: "Cast", Name: "CastInt8ToUint32", Operands: 1, Size: 32},
	{Group: "Cast", Name: "CastInt8ToUint64", Operands: 1, Size: 64},
	{Group: "Cast", Name: "CastInt16ToInt8", Operands: 1, Size: 8},
	{Group: "Cast", Name: "CastInt16ToInt32", Operands: 1, Size: 32},
	{Group: "Cast", Name: "CastInt16ToInt64", Operands: 1, Size: 64},
	{Group: "Cast", Name: "CastInt16ToUint8", Operands: 1, Size: 8},
	{Group: "Cast", Name: "CastInt16ToUint16", Operands: 1, Size: 16},
	{Group: "Cast", Name: "CastInt16ToUint32", Operands: 1, Size: 32},
	{Group: "Cast", Name: "CastInt16ToUint64", Operands: 1, Size: 64},
	{Group: "Cast", Name: "CastInt32ToInt8", Operands: 1, Size: 8},
	{Group: "Cast", Name: "CastInt32ToInt16", Operands: 1, Size: 16},
	{Group: "Cast", Name: "CastInt32ToInt64", Operands: 1, Size: 64},
	{Group: "Cast", Name: "CastInt32ToUint8", Operands: 1, Size: 8},
	{Group: "Cast", Name: "CastInt32ToUint16", Operands: 1, Size: 16},
	{Group: "Cast", Name: "CastInt32ToUint32", Operands: 1, Size: 32},
	{Group: "Cast", Name: "CastInt32ToUint64", Operands: 1, Size: 64},
	{Group: "Cast", Name: "CastInt64ToInt8", Operands: 1, Size: 8},
	{Group: "Cast", Name: "CastInt64ToInt16", Operands: 1, Size: 16},
	{Group: "Cast", Name: "CastInt64ToInt32", Operands: 1, Size: 32},
	{Group: "Cast", Name: "CastInt64ToUint8", Operands: 1, Size: 8},
	{Group: "Cast", Name: "CastInt64ToUint16", Operands: 1, Size: 16},
	{Group: "Cast", Name: "CastInt64ToUint32", Operands: 1, Size: 32},
	{Group: "Cast", Name: "CastInt64ToUint64", Operands: 1, Size: 64},
	{Group: "Cast", Name: "CastUint8ToInt8", Operands: 1, Size: 8},
	{Group: "Cast", Name: "CastUint8ToInt16", Operands: 1, Size: 16},
	{Group: "Cast", Name: "CastUint8ToInt32", Operands: 1, Size: 32},
	{Group: "Cast", Name: "CastUint8ToInt64", Operands: 1, Size: 64},
	{Group: "Cast", Name: "CastUint8ToUint16", Operands: 1, Size: 16},
	{Group: "Cast", Name: "CastUint8ToUint32", Operands: 1, Size: 32},
	{Group: "Cast", Name: "CastUint8ToUint64", Operands: 1, Size: 64},
	{Group: "Cast", Name: "CastUint16ToInt8", Operands: 1, Size: 8},
	{Group: "Cast", Name: "CastUint16ToInt16", Operands: 1, Size: 16},
	{Group: "Cast", Name: "CastUint16ToInt32", Operands: 1, Size: 32},
	{Group: "Cast", Name: "CastUint16ToInt64", Operands: 1, Size: 64},
	{Group: "Cast", Name: "CastUint16ToUint8", Operands: 1, Size: 8},
	{Group: "Cast", Name: "CastUint16ToUint32", Operands: 1, Size: 32},
	{Group: "Cast", Name: "CastUint16ToUint64", Operands: 1, Size: 64},
	{Group: "Cast", Name: "CastUint32ToInt8", Operands: 1, Size: 8},
	{Group: "Cast", Name: "CastUint32ToInt16", Operands: 1, Size: 16},
	{Group: "Cast", Name: "CastUint32ToInt32", Operands: 1, Size: 32},
	{Group: "Cast", Name: "CastUint32ToInt64", Operands: 1, Size: 64},
	{Group: "Cast", Name: "CastUint32ToUint8", Operands: 1, Size: 8},
	{Group: "Cast", Name: "CastUint32ToUint16", Operands: 1, Size: 16},
	{Group: "Cast", Name: "CastUint32ToUint64", Operands: 1, Size: 64},
	{Group: "Cast", Name: "CastUint64ToInt8", Operands: 1, Size: 8},
	{Group: "Cast", Name: "CastUint64ToInt16", Operands: 1, Size: 16},
	{Group: "Cast", Name: "CastUint64ToInt32", Operands: 1, Size: 32},
	{Group: "Cast", Name: "CastUint64ToInt64", Operands: 1, Size: 64},
	{Group: "Cast", Name: "CastUint64ToUint8", Operands: 1, Size: 8},
	{Group: "Cast", Name: "CastUint64ToUint16", Operands: 1, Size: 16},
	{Group: "Cast", Name: "CastUint64ToUint32", Operands: 1, Size: 32},
}
