# Copyright 2022 The Firefly Authors.
#
# Use of this source code is governed by a BSD 3-clause
# license that can be found in the LICENSE file.

[package]
name = "virtmem"
version = "0.1.0"
authors = ["Jamie Hall <the.sly.marbo@googlemail.com>"]
edition = "2018"

[lib]
name = "virtmem"
path = "lib.rs"

[dependencies]
align = {path = "../../utils/align"}
bootloader = {version = "=0.9.21", features = ["map_physical_memory"]}
linked_list_allocator = "=0.9.0"
memlayout = {path = "../memlayout"}
pretty = {path = "../../utils/pretty"}
physmem = {path = "../physmem"}
serial = {path = "../../drivers/serial"}
spin = "=0.9.2"
x86_64 = "=0.14.7"
