[package]
name = "kernel"
version = "0.1.0"
authors = ["Jamie Hall <the.sly.marbo@googlemail.com>"]
edition = "2018"

[dependencies]
bitflags = "=1.3.2"
bootloader = {version = "=0.9.19", features = ["map_physical_memory"]}
crossbeam = { version = "=0.8.1", default-features = false, features = ["alloc"] }
crossbeam-queue = {version = "=0.2.1", default-features = false, features = ["alloc"]}
lazy_static = {version = "=1.4.0", features = ["spin_no_std"]}
linked_list_allocator = "=0.9.0"
pic8259 = "=0.10.1"
raw-cpuid = {version = "=10.2.0", default-features = false}
spin = "=0.9.2"
uart_16550 = "=0.2.15"
volatile = "=0.4.4"
x86_64 = "=0.14.7"

[package.metadata.bootimage]
test-success-exit-code = 33    # (0x10 << 1) | 1
test-timeout = 300             # (in seconds)
test-args = [
	"-device", "isa-debug-exit,iobase=0xf4,iosize=0x04"
]
run-command = [
	"qemu-system-x86_64",
	"-drive", "format=raw,file={}",
	"-serial", "stdio",
	"-display", "none"
]

[package.metadata.bootloader]
boot-info-address = "0xffff800040000000"
kernel-stack-address = "0xffff80005554f000"
kernel-stack-size = 128
physical-memory-offset = "0xffff800080000000"

[[test]]
name = "should_panic"
harness = false

[[test]]
name = "stack_overflow"
harness = false
