[package]
name = "kernel"
version = "0.1.0"
authors = ["Jamie Hall <the.sly.marbo@googlemail.com>"]
edition = "2018"

[dependencies]
bootloader = { version = "=0.9.19", features = ["map_physical_memory"]}
lazy_static = { version = "=1.4.0", features = ["spin_no_std"]}
linked_list_allocator = "=0.9.0"
pic8259 = "=0.10.1"
spin = "=0.5.2"
uart_16550 = "=0.2.15"
volatile = "=0.2.6"
x86_64 = "=0.14.6"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[package.metadata.bootimage]
test-success-exit-code = 33    # (0x10 << 1) | 1
test-timeout = 300             # (in seconds)
test-args = [
	"-device", "isa-debug-exit,iobase=0xf4,iosize=0x04",
	"-serial", "stdio",
	"-display", "none"
]
run-command = [
	"qemu-system-x86_64",
	"-drive", "format=raw,file={}",
	"-serial", "stdio",
	"-display", "none"
]

[[test]]
name = "should_panic"
harness = false

[[test]]
name = "stack_overflow"
harness = false
