[package]
name = "kernel"
version = "0.1.0"
authors = ["Jamie Hall <the.sly.marbo@googlemail.com>"]
edition = "2018"

[dependencies]
bootloader = "0.9.5"
spin = "0.5.2"
volatile = "0.2.6"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[package.metadata.bootimage]
run-command = [
	"qemu-system-x86_64",
	"-drive", "format=raw,file={}",
	"-device", "e1000,mac=01:23:45:67:89:ab",
	"-m", "128M",
	"-cpu", "Haswell"
]
