# Copyright 2022 The Firefly Authors.
#
# Use of this source code is governed by a BSD 3-clause
# license that can be found in the LICENSE file.

[package]
name = "cpu"
version = "0.1.0"
authors = ["Jamie Hall <the.sly.marbo@googlemail.com>"]
edition = "2018"

[lib]
name = "cpu"
path = "lib.rs"

[dependencies]
lazy_static = {version = "=1.4.0", features = ["spin_no_std"]}
memlayout = {path = "../memory/memlayout"}
physmem = {path = "../memory/physmem"}
raw-cpuid = {version = "=10.2.0", default-features = false}
serial = {path = "../drivers/serial"}
virtmem = {path = "../memory/virtmem"}
x86_64 = "=0.14.7"
