# Copyright 2022 The Firefly Authors.
#
# Use of this source code is governed by a BSD 3-clause
# license that can be found in the LICENSE file.

[package]
name = "cpuid"
version = "0.1.0"
authors = ["Jamie Hall <the.sly.marbo@googlemail.com>"]
edition = "2018"

[lib]
name = "cpuid"
path = "lib.rs"

[dependencies]
raw-cpuid = {version = "=10.2.0", default-features = false}
serial = {path = "../drivers/serial"}
