# Copyright 2022 The Firefly Authors.
#
# Use of this source code is governed by a BSD 3-clause
# license that can be found in the LICENSE file.

[package]
name = "interrupts"
version = "0.1.0"
authors = ["Jamie Hall <the.sly.marbo@googlemail.com>"]
edition = "2018"

[lib]
name = "interrupts"
path = "lib.rs"

[dependencies]
lazy_static = {version = "=1.4.0", features = ["spin_no_std"]}
pic8259 = "=0.10.1"
segmentation = {path = "../segmentation"}
serial = {path = "../drivers/serial"}
spin = "=0.9.2"
x86_64 = "=0.14.7"
