# Copyright 2022 The Firefly Authors.
#
# Use of this source code is governed by a BSD 3-clause
# license that can be found in the LICENSE file.

[package]
name = "random"
version = "0.1.0"
authors = ["Jamie Hall <the.sly.marbo@googlemail.com>"]
edition = "2018"

[lib]
name = "random"
path = "lib.rs"

[dependencies]
chacha20 = "=0.8.1"
sha2 = {version = "=0.10.1", default-features = false, features = ["force-soft"]}
spin = "=0.9.2"
time = {path = "../time"}
x86_64 = "=0.14.7"
