###############################################################################
# @generated
# This file is auto-generated by the cargo-bazel tool.
#
# DO NOT MODIFY: Local changes may be replaced in future executions.
###############################################################################

package(default_visibility = ["//visibility:public"])

exports_files(
    [
        "cargo-bazel.json",
        "defs.bzl",
    ] + glob([
        "*.bazel",
    ]),
)

filegroup(
    name = "srcs",
    srcs = glob([
        "*.bazel",
        "*.bzl",
    ]),
)

# Workspace Member Dependencies
alias(
    name = "bit_field",
    actual = "@crates__bit_field-0.10.1//:bit_field",
    tags = ["manual"],
)
alias(
    name = "bitflags",
    actual = "@crates__bitflags-1.3.2//:bitflags",
    tags = ["manual"],
)
alias(
    name = "byteorder",
    actual = "@crates__byteorder-1.4.3//:byteorder",
    tags = ["manual"],
)
alias(
    name = "chacha20",
    actual = "@crates__chacha20-0.9.0//:chacha20",
    tags = ["manual"],
)
alias(
    name = "cpufeatures",
    actual = "@crates__cpufeatures-0.2.2//:cpufeatures",
    tags = ["manual"],
)
alias(
    name = "digest",
    actual = "@crates__digest-0.10.3//:digest",
    tags = ["manual"],
)
alias(
    name = "fixedvec",
    actual = "@crates__fixedvec-0.2.4//:fixedvec",
    tags = ["manual"],
)
alias(
    name = "hex-literal",
    actual = "@crates__hex-literal-0.3.4//:hex_literal",
    tags = ["manual"],
)
alias(
    name = "lazy_static",
    actual = "@crates__lazy_static-1.4.0//:lazy_static",
    tags = ["manual"],
)
alias(
    name = "libc",
    actual = "@crates__libc-0.2.121//:libc",
    tags = ["manual"],
)
alias(
    name = "linked_list_allocator",
    actual = "@crates__linked_list_allocator-0.9.1//:linked_list_allocator",
    tags = ["manual"],
)
alias(
    name = "llvm-tools",
    actual = "@crates__llvm-tools-0.1.1//:llvm_tools",
    tags = ["manual"],
)
alias(
    name = "managed",
    actual = "@crates__managed-0.8.0//:managed",
    tags = ["manual"],
)
alias(
    name = "pic8259",
    actual = "@crates__pic8259-0.10.2//:pic8259",
    tags = ["manual"],
)
alias(
    name = "raw-cpuid",
    actual = "@crates__raw-cpuid-10.3.0//:raw_cpuid",
    tags = ["manual"],
)
alias(
    name = "rlibc",
    actual = "@crates__rlibc-1.0.0//:rlibc",
    tags = ["manual"],
)
alias(
    name = "serde",
    actual = "@crates__serde-1.0.136//:serde",
    tags = ["manual"],
)
alias(
    name = "sha2",
    actual = "@crates__sha2-0.10.2//:sha2",
    tags = ["manual"],
)
alias(
    name = "smoltcp",
    actual = "@crates__smoltcp-0.8.0//:smoltcp",
    tags = ["manual"],
)
alias(
    name = "thiserror",
    actual = "@crates__thiserror-1.0.30//:thiserror",
    tags = ["manual"],
)
alias(
    name = "toml",
    actual = "@crates__toml-0.5.8//:toml",
    tags = ["manual"],
)
alias(
    name = "uart_16550",
    actual = "@crates__uart_16550-0.2.16//:uart_16550",
    tags = ["manual"],
)
alias(
    name = "usize_conversions",
    actual = "@crates__usize_conversions-0.2.0//:usize_conversions",
    tags = ["manual"],
)
alias(
    name = "volatile",
    actual = "@crates__volatile-0.4.4//:volatile",
    tags = ["manual"],
)
alias(
    name = "x86_64",
    actual = "@crates__x86_64-0.14.8//:x86_64",
    tags = ["manual"],
)
alias(
    name = "xmas-elf",
    actual = "@crates__xmas-elf-0.8.0//:xmas_elf",
    tags = ["manual"],
)
alias(
    name = "zero",
    actual = "@crates__zero-0.1.2//:zero",
    tags = ["manual"],
)

# Binaries
alias(
    name = "raw-cpuid__cpuid",
    actual = "@crates__raw-cpuid-10.3.0//:cpuid__bin",
    tags = ["manual"],
)
alias(
    name = "xmas-elf__xmas_elf",
    actual = "@crates__xmas-elf-0.8.0//:xmas_elf__bin",
    tags = ["manual"],
)
